// AUTO-GENERATED BY create_images.py

export const AmiiboBack = {
  blurhash: 'UFQ]sKof_Nni.9WFMdoN%MbFMxV]H;S1%hSe',
  aspectRatio: 0.7145790554414785,
  webpSources: [
    { src: '/images/amiibo-back-69.f5dffb941f.webp', width: 69 },
    { src: '/images/amiibo-back-278.65369cf35d.webp', width: 278 },
    { src: '/images/amiibo-back-174.23ca40e662.webp', width: 174 },
    { src: '/images/amiibo-back-348.38385430e7.webp', width: 348 }
  ],
  jpegSources: [
    { src: '/images/amiibo-back-174.d9a1bfbaee.jpeg', width: 174 },
    { src: '/images/amiibo-back-348.e9b1aa3ab2.jpeg', width: 348 },
    { src: '/images/amiibo-back-278.8779c5a23a.jpeg', width: 278 },
    { src: '/images/amiibo-back-69.b8967ba273.jpeg', width: 69 }
  ]
};
export const Wattam = {
  blurhash: 'U98p+Voz4nR%W,j]sof600WA?cs:t7j[RjfP',
  aspectRatio: 1.6699147381242387,
  webpSources: [
    { src: '/images/wattam-1096.af0281eaf3.webp', width: 1096 },
    { src: '/images/wattam-685.0a9c4a29c4.webp', width: 685 },
    { src: '/images/wattam-274.3355db5f2a.webp', width: 274 },
    { src: '/images/wattam-1371.4f2862b83b.webp', width: 1371 }
  ],
  jpegSources: [
    { src: '/images/wattam-1371.61cc194206.jpeg', width: 1371 },
    { src: '/images/wattam-274.4d7a012b82.jpeg', width: 274 },
    { src: '/images/wattam-1096.8ca9c03351.jpeg', width: 1096 },
    { src: '/images/wattam-685.a461dee4a6.jpeg', width: 685 }
  ]
};
export const NinjaLogo = {
  blurhash: 'U0TSUA%MfQ%M?bfQfQfQayfQfQfQ?bfQfQfQ',
  aspectRatio: 1.7811934900542497,
  webpSources: [
    { src: '/images/ninja-logo-197.3c50fb011a.webp', width: 197 },
    { src: '/images/ninja-logo-492.3ec11aba8c.webp', width: 492 },
    { src: '/images/ninja-logo-985.c1b7f65d23.webp', width: 985 },
    { src: '/images/ninja-logo-788.19aae98ad1.webp', width: 788 }
  ],
  jpegSources: [
    { src: '/images/ninja-logo-985.6d2d4a8c2e.jpeg', width: 985 },
    { src: '/images/ninja-logo-492.5734ede220.jpeg', width: 492 },
    { src: '/images/ninja-logo-788.73af424f4a.jpeg', width: 788 },
    { src: '/images/ninja-logo-197.82448f66f0.jpeg', width: 197 }
  ]
};
export const MarinaAbramovic = {
  blurhash: 'U8Rk2zofQ8oftlaeaKkCQ8aeo}aKnOkCkqf6',
  aspectRatio: 1.0,
  webpSources: [
    { src: '/images/marina-abramovic-100.799b26c372.webp', width: 100 },
    { src: '/images/marina-abramovic-500.a0fa87d548.webp', width: 500 },
    { src: '/images/marina-abramovic-400.1cc9cdccc8.webp', width: 400 },
    { src: '/images/marina-abramovic-250.accbd79a6f.webp', width: 250 }
  ],
  jpegSources: [
    { src: '/images/marina-abramovic-500.32413beddf.jpeg', width: 500 },
    { src: '/images/marina-abramovic-250.60680b606c.jpeg', width: 250 },
    { src: '/images/marina-abramovic-100.2e95deb449.jpeg', width: 100 },
    { src: '/images/marina-abramovic-400.424f46e2e5.jpeg', width: 400 }
  ]
};
export const AmiiboFront = {
  blurhash: 'UrIF*=s:JCt4?dofxaodD~oL${j?t9WCofj@',
  aspectRatio: 0.7175257731958763,
  webpSources: [
    { src: '/images/amiibo-front-348.24640aaf2b.webp', width: 348 },
    { src: '/images/amiibo-front-69.b590c69cfb.webp', width: 69 },
    { src: '/images/amiibo-front-174.dbfebdb985.webp', width: 174 },
    { src: '/images/amiibo-front-278.d35333c069.webp', width: 278 }
  ],
  jpegSources: [
    { src: '/images/amiibo-front-348.c4f93e352d.jpeg', width: 348 },
    { src: '/images/amiibo-front-174.afba1af04c.jpeg', width: 174 },
    { src: '/images/amiibo-front-278.c42b0965e4.jpeg', width: 278 },
    { src: '/images/amiibo-front-69.65c12ce630.jpeg', width: 69 }
  ]
};
export const MusicClientsRecord = {
  blurhash: 'UE9tJsRj4nWBxuoLRjj[00ay_3oyM{WBxtWB',
  aspectRatio: 1.0,
  webpSources: [
    { src: '/images/music-clients-record-1080.73531f2a10.webp', width: 1080 },
    { src: '/images/music-clients-record-540.96ce17ca41.webp', width: 540 },
    { src: '/images/music-clients-record-864.2ffbedd5ae.webp', width: 864 },
    { src: '/images/music-clients-record-216.464b4fb322.webp', width: 216 }
  ],
  jpegSources: [
    { src: '/images/music-clients-record-216.06dee38e42.jpeg', width: 216 },
    { src: '/images/music-clients-record-1080.0c343c5697.jpeg', width: 1080 },
    { src: '/images/music-clients-record-540.a76ce2cf9e.jpeg', width: 540 },
    { src: '/images/music-clients-record-864.401adcf5a7.jpeg', width: 864 }
  ]
};
