// AUTO-GENERATED BY create_images.py

export const NinjaLogo = {
    blurhash: 'U0TSUA%MfQ%M?bfQfQfQayfQfQfQ?bfQfQfQ',
    aspectRatio: 1.7811934900542497,
    webpSources: [{ src: '/images/ninja-logo-197.c19b585f4a.webp', width: 197 },{ src: '/images/ninja-logo-985.c1b7f65d23.webp', width: 985 },{ src: '/images/ninja-logo-492.4bf1e2b912.webp', width: 492 },{ src: '/images/ninja-logo-788.4c9e939e05.webp', width: 788 }],
    jpegSources: [{ src: '/images/ninja-logo-492.37d395c4a2.jpeg', width: 492 },{ src: '/images/ninja-logo-788.ef5ef9bd98.jpeg', width: 788 },{ src: '/images/ninja-logo-197.4bf3362319.jpeg', width: 197 },{ src: '/images/ninja-logo-985.6d2d4a8c2e.jpeg', width: 985 }],
};
export const AmiiboBack = {
    blurhash: 'UFQ]sKof_Nni.9WFMdoN%MbFMxV]H;S1%hSe',
    aspectRatio: 0.7145790554414785,
    webpSources: [{ src: '/images/amiibo-back-278.b2dbc0ddd8.webp', width: 278 },{ src: '/images/amiibo-back-69.e19027cad8.webp', width: 69 },{ src: '/images/amiibo-back-174.598ef15fa0.webp', width: 174 },{ src: '/images/amiibo-back-348.38385430e7.webp', width: 348 }],
    jpegSources: [{ src: '/images/amiibo-back-348.fc9919e591.jpeg', width: 348 },{ src: '/images/amiibo-back-174.0af51b6f0b.jpeg', width: 174 },{ src: '/images/amiibo-back-278.2e85a70f5b.jpeg', width: 278 },{ src: '/images/amiibo-back-69.4c4567ca8b.jpeg', width: 69 }],
};
export const AmiiboFront = {
    blurhash: 'UrIF*=s:JCt4?dofxaodD~oL${j?t9WCofj@',
    aspectRatio: 0.7175257731958763,
    webpSources: [{ src: '/images/amiibo-front-348.24640aaf2b.webp', width: 348 },{ src: '/images/amiibo-front-174.ad30ff2178.webp', width: 174 },{ src: '/images/amiibo-front-278.568bb3d9ce.webp', width: 278 },{ src: '/images/amiibo-front-69.8f31fbfebe.webp', width: 69 }],
    jpegSources: [{ src: '/images/amiibo-front-69.21471b4002.jpeg', width: 69 },{ src: '/images/amiibo-front-278.9c1837ec8a.jpeg', width: 278 },{ src: '/images/amiibo-front-174.83f23ecd38.jpeg', width: 174 },{ src: '/images/amiibo-front-348.8c6491b023.jpeg', width: 348 }],
};
